.TH COLLATZ 1
.SH NAME
collatz \- Command line interface to compute & print the Collatz conjecture.
.SH SYNOPSIS
.B collatz
\fISTART\fR
.SH DESCRIPTION
.B collatz
is a command line interface that can compute & print the Collatz conjecture.
.SH OPTIONS
.TP
.BR \fISTART\fR
Set the starting point for the Collatz conjecture. It should be an integer greater or equal to one.
