.TH COLLATZ 1
.SH NAME
collatz \- Command line interface to compute & print the Collatz conjecture.
.SH VERSION
0.5.0
.SH SYNOPSIS
.B collatz
[\fIOPTIONS\fR] \fISTART\fR
.SH DESCRIPTION
.B collatz
is a command line interface that can compute & print the Collatz conjecture.
.SH ARGUMENT
.TP
.BR \fISTART\fR
Set the starting point for the Collatz conjecture. It should be an integer greater or equal to one.
.SH OPTIONS
.TP
.BR \-\-version
Get the version of the currently installed binary.
.SH AUTHOR
Amin NAIRI <\fIhttps://github.com/aminnairi\fR>
.SH SEE ALSO
GitHub repository at \fIhttps://github.com/aminnairi/collatz\fR and \fIhttps://github.com/aminnairi/collatz/issues\fR for submitting a new feature request or open an issue.

